### ISSUE TITLE
[Suggestion][District Extender] Beehive hook

### ISSUE THREAD

**Issue by VaelophisNyx** [Procdox/TB_WanderDisable#2]
It'd be nice if we could modify the range and speed of the beehive with District Extender, which while a little out of scope, would make use of them much simpler. (also would be nice if they weren't arbitrarily Ground Only)

**Comment by AlexBig101** [comment]
I don’t know where to write my change about fashion? Do you need to create a separate topic ?? I was hoping to see a place under the mod for a simple comment, but I couldn't find it.
In general, I would like to thank you for the opportunity to make roads all over the map belonging to and reaching the first initial area with a green line. As a beginner, I play this game at first, and then, when I understand everything in this game, I will complicate it. Thanks again!
(translation from Russian into English via google translator)
